### ISSUE TITLE
build with tsc on wppconnect 1.9.4

### ISSUE THREAD

**Issue by antirek** [wppconnect-team/wppconnect#609]
build project with tsc
and error in Model.d.ts

typescript 4.2.4
wppconnect 1.9.4

``````
> tsc
node_modules/@wppconnect/wa-js/dist/whatsapp/models/Model.d.ts:19:5 - error TS1131: Property or signature expected.

19     get attributes(): P & S;
       ~~~

node_modules/@wppconnect/wa-js/dist/whatsapp/models/Model.d.ts:19:9 - error TS1005: ';' expected.

19     get attributes(): P & S;
           ~~~~~~~~~~

node_modules/@wppconnect/wa-js/dist/whatsapp/models/Model.d.ts:19:21 - error TS1005: ';' expected.

19     get attributes(): P & S;
                       ~

node_modules/@wppconnect/wa-js/dist/whatsapp/models/Model.d.ts:20:9 - error TS1005: ';' expected.

20     get isState(): true;
           ~~~~~~~

node_modules/@wppconnect/wa-js/dist/whatsapp/models/Model.d.ts:20:18 - error TS1005: ';' expected.

20     get isState(): true;
                    ~

node_modules/@wppconnect/wa-js/dist/whatsapp/models/Model.d.ts:21:5 - error TS1128: Declaration or statement expected.

21     readonly mirrorMask: {
       ~~~~~~~~

node_modules/@wppconnect/wa-js/dist/whatsapp/models/Model.d.ts:22:63 - error TS1005: ';' expected.

22         [key in keyof (P & S & D) as `change:${string & key}`]: number;
                                                                 ~

node_modules/@wppconnect/wa-js/dist/whatsapp/models/Model.d.ts:24:13 - error TS1005: ';' expected.

24     toJSON(): P;
               ~

node_modules/@wppconnect/wa-js/dist/whatsapp/models/Model.d.ts:25:16 - error TS1005: ';' expected.

25     serialize(): P;
                  ~

node_modules/@wppconnect/wa-js/dist/whatsapp/models/Model.d.ts:26:1 - error TS1128: Declaration or statement expected.

26 };
   ~


Found 10 errors.

``````

**Comment by edgardmessias** [comment]
I don't know what happened in your case, because in my local environment is working like a charm

**Comment by antirek** [comment]
@edgardmessias what version of tsc you use? I used tsc@4.2 

now I update to 4.4.4 and receive error
`````
node_modules/@wppconnect/wa-js/dist/auth/Auth.d.ts:16:8 - error TS1259: Module '"/node_modules/emittery/index"' can only be default-imported using the 'esModuleInterop' flag

16 import Emittery from 'emittery';
          ~~~~~~~~

  node_modules/emittery/index.d.ts:432:1
    432 export = Emittery;
        ~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

`````

**Comment by antirek** [comment]
also I updated wppconnect to 1.10.0

**Comment by antirek** [comment]
it's fixed by "allowSyntheticDefaultImports": true in ts config compilerOptions

**Comment by edgardmessias** [comment]
Add emittery as a devDepency

> 
> @edgardmessias what version of tsc you use? I used tsc@4.2 
> 
> now I update to 4.4.4 and receive error
> `````
> node_modules/@wppconnect/wa-js/dist/auth/Auth.d.ts:16:8 - error TS1259: Module '"/node_modules/emittery/index"' can only be default-imported using the 'esModuleInterop' flag
> 
> 16 import Emittery from 'emittery';
>           ~~~~~~~~
> 
>   node_modules/emittery/index.d.ts:432:1
>     432 export = Emittery;
>         ~~~~~~~~~~~~~~~~~~
>     This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
> 
> `````

**Comment by antirek** [comment]
I think that is all ))
